spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id:
            client-secret:
            provider: google
            redirect-uri: "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
              - email
              - profile
              - openid
          facebook:
            client-id: 1561746374577646
            client-secret: f01341a03fc4a6c5ebcc5c848ed22446
            provider: facebook
            redirect-uri: "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
              - email
              - public_profile
              

openapi:
  info:
    title: Railway
    description: Railway
    version: 1.0.0
    contact:
    name: Tien Tran Cong
    email: trancongtien406@gmail.com
  dev-url: http://localhost:8080
app:
  tokenSecret: 926D96C90030DD58429D2751AC1BDBBC
  tokenExpirationMsec: 864000000
  authorizedRedirectUris:
    - http://localhost:5000/oauth2/redirect
hostname: localhost:5000
